env               = "dev"
billing_tag_value = "GCOrgResolver"
region            = "ca-central-1"
github_org        = "cds-snc"
github_repo       = "gcorg-resolver"
state_bucket      = "gcorg-resolver-dev-tfstate-a7f3k9"
