account_id        = "624627265345"
env               = "dev"
billing_tag_value = "GCOrgResolver"
region            = "ca-central-1"
domain_name       = "donairpoutine.com"
subdomain         = "gcorgs"